name: CI/CD Next.js → Azure App Service
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: idwebappnext02
  AZURE_RESOURCE_GROUP: IDRG_URUSLEGAL01
  NODE_VERSION: "20"
  NEXT_TELEMETRY_DISABLED: "1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # 👉 bundel runtime: .next, public, node_modules, package.json, lockfile
      - name: Prepare deploy bundle
        run: |
          mkdir -p deploy
          cp -r .next deploy/.next
          [ -d public ] && cp -r public deploy/public || true
          cp package.json package-lock.json deploy/
          [ -f next.config.ts ] && cp next.config.ts deploy/ || true
          [ -f next.config.js ] && cp next.config.js deploy/ || true
          [ -f tsconfig.json ] && cp tsconfig.json deploy/ || true
          cp -r node_modules deploy/node_modules

      - name: Zip bundle
        run: |
          cd deploy
          zip -r ../out.zip .

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ZIP to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: out.zip
