name: Deploy Next.js to Azure App Service (SP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: idwebappnext02
  AZURE_RESOURCE_GROUP: IDRG_URUSLEGAL01
  NODE_VERSION: "20"
  NEXT_TELEMETRY_DISABLED: "1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Archive app (zip)
        run: |
          mkdir -p out
          zip -r out/app.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Azure login (Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ZIP to App Service
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
              --name "${{ env.AZURE_WEBAPP_NAME }}" \
              --type zip \
              --src-path out/app.zip

      - name: Logout
        if: always()
        run: az logout
