name: Deploy Next.js (Standalone) to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-standalone-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js (standalone)
        env:
          NEXT_TELEMETRY_DISABLED: "1"
        run: npm run build

      - name: Verify build assets (CSS & standalone)
        run: |
          echo "== .next/standalone =="
          ls -la .next/standalone
          echo "== .next/static/css =="
          ls -la .next/static/css || true

      - name: Create deployment package (standalone)
        run: |
          mkdir -p dist
          zip -r dist/app.zip \
            .next/standalone \
            .next/static \
            public \
            package.json package-lock.json \
            --exclude "**/.git/**" "**/.github/**" "**/node_modules/**"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "idwebappnext02"
          package: "dist/app.zip"


