- name: Build Next.js
  env:
    NEXT_TELEMETRY_DISABLED: "1"
  run: npm run build

- name: Verify build assets (CSS & standalone)
  run: |
    echo "== .next/static/css =="
    ls -la .next/static/css || true
    echo "== .next/standalone =="
    ls -la .next/standalone || true

- name: Create deployment package (standalone)
  run: |
    mkdir -p dist
    zip -r dist/app.zip \
      .next/standalone \
      .next/static \
      public \
      package.json package-lock.json \
      --exclude "**/.git/**" "**/.github/**" "**/node_modules/**"
