name: Deploy Next.js to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-azure-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Optional: set vars untuk build-time (bukan secret). Runtime env ambil dari Azure.
      - name: Build Next.js
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          NEXT_PUBLIC_SITE_URL: https://layanan.uruslegal.id
        run: npm run build

      # Buang devDependencies biar paket deploy lebih ramping
      - name: Prune devDependencies
        run: npm prune --omit=dev

      # Zip semua yang dibutuhkan untuk runtime:
      # - package.json, package-lock.json
      # - .next (hasil build), public, node_modules, next.config.js, dll.
      - name: Create deployment package
        run: |
          mkdir -p dist
          zip -r dist/app.zip \
            .next public node_modules \
            package.json package-lock.json \
            next.config.js \
            --exclude "**/.git/**" "**/.github/**" "**/node_modules/.cache/**"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "idwebappnext02"
          package: "dist/app.zip"
